services:
  adguardhome:
    image: 'adguard/adguardhome:latest'
    container_name: 'adguard'
    hostname: 'adguard'
    restart: 'unless-stopped'
    user: '1000:1000'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - './work:/opt/adguardhome/work'
      - './config:/opt/adguardhome/conf'
    ports:
      # Plain DNS
      - '1025:1025/tcp'
      - '1025:1025/udp'
      # AdGuard Home Admin Panel as well as DNS-over-HTTPS
      - '80:80/tcp'
      - '443:443/tcp'
      - '443:443/udp'
      - '3000:3000/tcp'
      # DNS-over-TLS
      - '853:853/tcp'
      # DNS-over-QUIC
      - '784:784/udp'
      - '853:853/udp'
      - '8853:8853/udp'
      # DNSCrypt
      - '5443:5443/tcp'
      - '5443:5443/udp'